package constant

const (
	RABBITMQ_HOST                         string = "RABBITMQ_HOST"
	RABBITMQ_PORT                         string = "RABBITMQ_PORT"
	RABBITMQ_USER                         string = "RABBITMQ_USER"
	RABBITMQ_PASSWORD                     string = "RABBITMQ_PASSWORD"
	RABBITMQ_VHOST                        string = "RABBITMQ_VHOST"
	RABBITMQ_HEARTBEAT_INTERVAL           string = "RABBITMQ_HEARTBEAT_INTERVAL"
	RABBITMQ_HEALTH_CHECK_INTERVAL        string = "RABBITMQ_HEALTH_CHECK_INTERVAL"
	RABBITMQ_RECONNECT_MAX_RETRIES        string = "RABBITMQ_RECONNECT_MAX_RETRIES"
	RABBITMQ_RECONNECT_INTERVAL           string = "RABBITMQ_RECONNECT_INTERVAL"
	RABBITMQ_CIRCUIT_BREAKER_MAX_FAILURES string = "RABBITMQ_CIRCUIT_BREAKER_MAX_FAILURES"
	RABBITMQ_CIRCUIT_BREAKER_TIMEOUT      string = "RABBITMQ_CIRCUIT_BREAKER_TIMEOUT"
)

const (
	WORKER_RETRY_QUEUE_DECLARE_NAME = "%v.retry"
	WORKER_DLQ_NAME                 = "%v.dlq"
)

// Worker Queue Names
const (
	WORKER_MULTI_POSTING = "worker_multi_posting"
	WORKER_EMAIL         = "worker_email"
	WORKER_NOTIFICATION  = "worker_notification"
)

// Worker Queue Names
const (
	WORKER_QUEUE_MULTI_POSTING = "multi_posting_queue"
	// WORKER_QUEUE_EMAIL         = "email_queue"
	// WORKER_QUEUE_NOTIFICATION  = "notification_queue"
)

// Worker Config Keys
const (
	WORKER_MULTI_POSTING_ENABLED       = "WORKER_MULTI_POSTING_ENABLED"
	WORKER_MULTI_POSTING_RETRY_ENABLED = "WORKER_MULTI_POSTING_RETRY_ENABLED"
	WORKER_MULTI_POSTING_MAX_RETRY     = "WORKER_MULTI_POSTING_MAX_RETRY"
	WORKER_MULTI_POSTING_CONCURRENCY   = "WORKER_MULTI_POSTING_CONCURRENCY"

	// WORKER_EMAIL_ENABLED       = "WORKER_EMAIL_ENABLED"
	// WORKER_EMAIL_RETRY_ENABLED = "WORKER_EMAIL_RETRY_ENABLED"
	// WORKER_EMAIL_MAX_RETRY     = "WORKER_EMAIL_MAX_RETRY"
	// WORKER_EMAIL_CONCURRENCY   = "WORKER_EMAIL_CONCURRENCY"

	// WORKER_NOTIFICATION_ENABLED       = "WORKER_NOTIFICATION_ENABLED"
	// WORKER_NOTIFICATION_RETRY_ENABLED = "WORKER_NOTIFICATION_RETRY_ENABLED"
	// WORKER_NOTIFICATION_MAX_RETRY     = "WORKER_NOTIFICATION_MAX_RETRY"
	// WORKER_NOTIFICATION_CONCURRENCY   = "WORKER_NOTIFICATION_CONCURRENCY"
)

// Worker Message Status
const (
	WORKER_MESSAGE_STATUS_PENDING    = "PENDING"
	WORKER_MESSAGE_STATUS_PROCESSING = "PROCESSING"
	WORKER_MESSAGE_STATUS_SUCCESS    = "SUCCESS"
	WORKER_MESSAGE_STATUS_FAILED     = "FAILED"
	WORKER_MESSAGE_STATUS_RETRY      = "RETRY"
)

// Scheduled Job Config Keys
const (
	JOB_SCHEDULED_MULTI_POSTING_ENABLED  = "JOB_SCHEDULED_MULTI_POSTING_ENABLED"
	JOB_SCHEDULED_MULTI_POSTING_SCHEDULE = "JOB_SCHEDULED_MULTI_POSTING_SCHEDULE"

	JOB_AUTO_CLOSE_STALE_RETURNS_ENABLED  = "JOB_AUTO_CLOSE_STALE_RETURNS_ENABLED"
	JOB_AUTO_CLOSE_STALE_RETURNS_SCHEDULE = "JOB_AUTO_CLOSE_STALE_RETURNS_SCHEDULE"

	JOB_DAILY_SALES_RETURN_SUMMARY_ENABLED  = "JOB_DAILY_SALES_RETURN_SUMMARY_ENABLED"
	JOB_DAILY_SALES_RETURN_SUMMARY_SCHEDULE = "JOB_DAILY_SALES_RETURN_SUMMARY_SCHEDULE"
)

// Default Cron Schedules
const (
	CRON_DAILY_MIDNIGHT = "0 0 * * *"    // Every day at 00:00
	CRON_DAILY_5AM      = "0 5 * * *"    // Every day at 05:00
	CRON_DAILY_NOON     = "0 12 * * *"   // Every day at 12:00
	CRON_TWICE_DAILY    = "0 0,12 * * *" // Every day at 00:00 and 12:00
	CRON_HOURLY         = "0 * * * *"    // Every hour
	CRON_EVERY_5_MIN    = "*/5 * * * *"  // Every 5 minutes
	CRON_EVERY_MINUTE   = "* * * * *"    // Every minute
)
