package constant

const (
	RABBITMQ_HOST                         string = "RABBITMQ_HOST"
	RABBITMQ_PORT                         string = "RABBITMQ_PORT"
	RABBITMQ_USER                         string = "RABBITMQ_USER"
	RABBITMQ_PASSWORD                     string = "RABBITMQ_PASSWORD"
	RABBITMQ_VHOST                        string = "RABBITMQ_VHOST"
	RABBITMQ_HEARTBEAT_INTERVAL           string = "RABBITMQ_HEARTBEAT_INTERVAL"
	RABBITMQ_HEALTH_CHECK_INTERVAL        string = "RABBITMQ_HEALTH_CHECK_INTERVAL"
	RABBITMQ_RECONNECT_MAX_RETRIES        string = "RABBITMQ_RECONNECT_MAX_RETRIES"
	RABBITMQ_RECONNECT_INTERVAL           string = "RABBITMQ_RECONNECT_INTERVAL"
	RABBITMQ_CIRCUIT_BREAKER_MAX_FAILURES string = "RABBITMQ_CIRCUIT_BREAKER_MAX_FAILURES"
	RABBITMQ_CIRCUIT_BREAKER_TIMEOUT      string = "RABBITMQ_CIRCUIT_BREAKER_TIMEOUT"
)

const (
	WORKER_RETRY_QUEUE_DECLARE_NAME = "%v.retry"
	WORKER_DLQ_NAME                 = "%v.dlq"
)
